//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediMonitor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediMonitor.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Survey.
        /// </summary>
        internal static string Activate_Survey {
            get {
                return ResourceManager.GetString("Activate Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string App_Settings {
            get {
                return ResourceManager.GetString("App Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is updated.
        /// </summary>
        internal static string App_Updated {
            get {
                return ResourceManager.GetString("App Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because you receive medication from Regenboog Apotheek, we ask you to fill in a short daily survey..
        /// </summary>
        internal static string App_Welcome {
            get {
                return ResourceManager.GetString("App Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the application..
        /// </summary>
        internal static string AppLoadError {
            get {
                return ResourceManager.GetString("AppLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm choice.
        /// </summary>
        internal static string Confirm_choice {
            get {
                return ResourceManager.GetString("Confirm choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Surveys.
        /// </summary>
        internal static string Current_Surveys {
            get {
                return ResourceManager.GetString("Current Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data.
        /// </summary>
        internal static string Download_data {
            get {
                return ResourceManager.GetString("Download data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your data from this app..
        /// </summary>
        internal static string Download_data_Details {
            get {
                return ResourceManager.GetString("Download data Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter today&apos;s score..
        /// </summary>
        internal static string Enter_today_s_score {
            get {
                return ResourceManager.GetString("Enter today\'s score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dddd MMMM dd yyyy}.
        /// </summary>
        internal static string FullDateFormat {
            get {
                return ResourceManager.GetString("FullDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code that is included in the package..
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the application....
        /// </summary>
        internal static string LoadingApplication {
            get {
                return ResourceManager.GetString("LoadingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Entry.
        /// </summary>
        internal static string Manual_Entry {
            get {
                return ResourceManager.GetString("Manual Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text beneath the QR code..
        /// </summary>
        internal static string Manual_Entry_Info {
            get {
                return ResourceManager.GetString("Manual Entry Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMediMonitor has been updated.
        /// </summary>
        internal static string MediMonitor_updated {
            get {
                return ResourceManager.GetString("MediMonitor updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Sign in and try again..
        /// </summary>
        internal static string NoSessionEx {
            get {
                return ResourceManager.GetString("NoSessionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the internet.        ///Connect and try again..
        /// </summary>
        internal static string Not_connected {
            get {
                return ResourceManager.GetString("Not connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Surveys.
        /// </summary>
        internal static string Previous_Surveys {
            get {
                return ResourceManager.GetString("Previous Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Agreement.
        /// </summary>
        internal static string PrivacyAgreement {
            get {
                return ResourceManager.GetString("PrivacyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.multitaskict.nl/privacyverklaring-medimonitor/.
        /// </summary>
        internal static string PrivacyUrl {
            get {
                return ResourceManager.GetString("PrivacyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all data.
        /// </summary>
        internal static string Remove_all_data {
            get {
                return ResourceManager.GetString("Remove all data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove data.
        /// </summary>
        internal static string Remove_data {
            get {
                return ResourceManager.GetString("Remove data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your data from this app..
        /// </summary>
        internal static string Remove_data_Details {
            get {
                return ResourceManager.GetString("Remove data Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove local data.
        /// </summary>
        internal static string Remove_local_data {
            get {
                return ResourceManager.GetString("Remove local data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove data because of a server error..
        /// </summary>
        internal static string RemoveDataError {
            get {
                return ResourceManager.GetString("RemoveDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        internal static string Scan_QR {
            get {
                return ResourceManager.GetString("Scan QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in error.
        /// </summary>
        internal static string Sign_In_Error {
            get {
                return ResourceManager.GetString("Sign In Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign off.
        /// </summary>
        internal static string Sign_off {
            get {
                return ResourceManager.GetString("Sign off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to sign off?.
        /// </summary>
        internal static string Sign_off_Confirm {
            get {
                return ResourceManager.GetString("Sign off Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign off from the application..
        /// </summary>
        internal static string Sign_Off_Details {
            get {
                return ResourceManager.GetString("Sign Off Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        internal static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Medication.
        /// </summary>
        internal static string Survey_Medication {
            get {
                return ResourceManager.GetString("Survey Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are you feeling today?.
        /// </summary>
        internal static string Survey_Question {
            get {
                return ResourceManager.GetString("Survey Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your survey response has been saved. Connect to the internet to synchronise..
        /// </summary>
        internal static string Survey_saved {
            get {
                return ResourceManager.GetString("Survey saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a lower score if you are feeling better..
        /// </summary>
        internal static string Survey_Score_Description {
            get {
                return ResourceManager.GetString("Survey Score Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a score between 1 and 7..
        /// </summary>
        internal static string Survey_Score_Info {
            get {
                return ResourceManager.GetString("Survey Score Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your survey response has been sent..
        /// </summary>
        internal static string Survey_sent {
            get {
                return ResourceManager.GetString("Survey sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronise.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation completed.
        /// </summary>
        internal static string Sync_Complete {
            get {
                return ResourceManager.GetString("Sync Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to try again?.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code not suuported..
        /// </summary>
        internal static string Unsupported_QR {
            get {
                return ResourceManager.GetString("Unsupported QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to continue, we need to update the database. You might need to sign in again using the QR code..
        /// </summary>
        internal static string Update_Data {
            get {
                return ResourceManager.GetString("Update Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        internal static string User_Settings {
            get {
                return ResourceManager.GetString("User Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
